config/routes.rb
Rails.application.routes.draw do
    
    #get 'sessions/new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #resources :favoritas
    #resources :user
    # get '/', to: 'musicas#index', as: 'index'
    root:to => 'musicas#index'
    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'
    get 'sign_out'  => 'sessions#destroy'

    get 'favoritas' =>'favoritas#index'
    

    get '/users/login' => 'users#login'

    get '/busca' => 'busca#index'

    get '/ajax/favoritar' => 'musicas#favoritar'

    post  '/admin/generos/save' => 'admin#saveGeneros'
    get '/admin/generos' => 'admin#generos'

    post  '/admin/artistas/save' => 'admin#saveArtistas'
    get '/admin/artistas' => 'admin#artistas'

    post  '/admin/musicas/save' => 'admin#saveMusicas'
    get '/admin/musicas' => 'admin#musicas'

    
    resources :users

    

    
    

end

app/views/admin/_form_artista.html.erb
<%= form_for @artista, method: :post, url: admin_artistas_save_path do |g| %>

    <h2>Editar/Atualizar Gêneros </h2>
    <%= g.hidden_field :id_artista %>
    <div class="field">
        <%= g.label :nome %>
        <%= g.text_field :nome %>
    </div>
    <div class="field">
        <%= g.label :url_thumb %>
        <%= g.text_field :thumb %>
    </div>

    <div class="field">
        <%= g.label :genero %>
        <select name='artista[id_genero]'>
            <option value=''>Selecionar Gênero</option>
            <% @generos.each  do |ge| %>
                <option <%= (@artista.genero != nil && ge.id_genero == @artista.genero.id_genero) ? 'selected="selected"' : '' %> value="<%= ge.id_genero %>"><%= ge.nome %></option>
            <% end%>
        </select>
    </div>
                
                
                <div class="actions">
                            <%= g.submit "Salvar"%>
                            <div class='clearfix'></div>
                </div>
    <% end %>

    <style>
        .content-overlay .field select{
            width: 60%;
            text-align: left;
            display: inline-block;
            padding: 10px 5px;
            border-radius: 5px;
            border: 1px #cccccc solid;
            margin-left: 10px;
        }
    </style>

app/views/admin/_form_genero.html.erb
<%= form_for @genero, method: :post, url: admin_generos_save_path do |g| %>

    <h2>Editar/Atualizar Gêneros </h2>
    <%= g.hidden_field :id_genero %>
    <div class="field">
    <%= g.label :nome %>
    <%= g.text_field :nome %>
                    
                            
                </div>
                
                
                <div class="actions">
                            <%= g.submit "Salvar"%>
                            <div class='clearfix'></div>
                </div>
    <% end %>

app/views/admin/_form_musica.html.erb
<%= form_for @musica, method: :post, url: admin_musicas_save_path do |g| %>

    <h2>Editar/Atualizar Gêneros </h2>
    <%= g.hidden_field :id_musica %>
    <div class="field">
    <%= g.label :nome %>
    <%= g.text_field :nome %>
    </div>

    <div class="field">
    <%= g.label :'Url do MP3' %>
    <%= g.text_field :caminho %>
    </div>

    <div class="field">
        <%= g.label :artista %>
        <select name='musica[id_artista]'>
            <option value=''>Selecionar Artista</option>
            <% @artistas.each  do |ge| %>
                <option <%= (@musica.artista != nil && ge.id_artista == @musica.artista.id_artista) ? 'selected="selected"' : '' %> value="<%= ge.id_genero %>"><%= ge.nome %></option>
            <% end%>
        </select>
    </div>

                
                <div class="actions">
                            <%= g.submit "Salvar"%>
                            <div class='clearfix'></div>
                </div>
    <% end %>

app/views/admin/artistas.html.erb
<% content_for :content do %>


	<div class='content-overlay'>
		<h2>Artistas</h2>


		<table>
			<thead>
				<tr>
					<th>
						ID
					</th>
					<th>
						Nome
					</th>
					<th>
						Ação
					</th>
				</tr>
			</thead>

			<tbody>
			<% @artistas.each do |g| %>
				<tr>
					<td> <%= g.id_artista %></td>
					<td> <%= g.nome %></td>
					<td> 
						<%= link_to "/admin/artistas?id_artista=#{g.id_artista}&acao=editar",:class=>'btn-send' do %>
        					Editar
      					<% end %>
      					 |
      					 <%= link_to "/admin/artistas?id_artista=#{g.id_artista}&acao=apagar",:class=>'btn-send' do %>
        					Apagar
      					<% end %>

					</td>
				</tr>
			<% end %>
				
			</tbody>
		</table>

		<%= link_to "/admin/artistas" do %>
			Novo Registro
		<% end %>






	</div>

	<div class='content-overlay'>
		<%= render 'form_artista' %>
	</div>




	<style>
	.content-overlay table {
	    border-collapse: collapse;
	    width: 100%;
	}

	.content-overlay th,.content-overlay  td {
	    text-align: left;
	    padding: 8px;
	    color:#000000;
	}

	.content-overlay  tr:nth-child(even){background-color: #f2f2f2}

	.content-overlay  th {
	    background-color: #000000;
	    color: white;
	}
	</style>







<% end %>

app/views/admin/generos.html.erb
<% content_for :content do %>


	<div class='content-overlay'>
		<h2>Estilos Musicais</h2>


		<table>
			<thead>
				<tr>
					<th>
						ID
					</th>
					<th>
						Nome
					</th>
					<th>
						Ação
					</th>
				</tr>
			</thead>

			<tbody>
			<% @generos.each do |g| %>
				<tr>
					<td> <%= g.id_genero %></td>
					<td> <%= g.nome %></td>
					<td> 
						<%= link_to "/admin/generos?id_genero=#{g.id_genero}&acao=editar",:class=>'btn-send' do %>
        					Editar
      					<% end %>
      					 |
      					 <%= link_to "/admin/generos?id_genero=#{g.id_genero}&acao=apagar",:class=>'btn-send' do %>
        					Apagar
      					<% end %>

					</td>
				</tr>
			<% end %>
				
			</tbody>
		</table>

		<%= link_to "/admin/generos" do %>
			Novo Registro
		<% end %>






	</div>

	<div class='content-overlay'>
		<%= render 'form_genero' %>
	</div>




	<style>
	.content-overlay table {
	    border-collapse: collapse;
	    width: 100%;
	}

	.content-overlay th,.content-overlay  td {
	    text-align: left;
	    padding: 8px;
	    color:#000000;
	}

	.content-overlay  tr:nth-child(even){background-color: #f2f2f2}

	.content-overlay  th {
	    background-color: #000000;
	    color: white;
	}
	</style>







<% end %>

app/views/admin/musicas.html.erb
<% content_for :content do %>


	<div class='content-overlay'>
		<h2>Estilos Musicais</h2>


		<table>
			<thead>
				<tr>
					<th>
						ID
					</th>
					<th>
						Nome
					</th>
					<th>
						Ação
					</th>
				</tr>
			</thead>

			<tbody>
			<% @musicas.each do |g| %>
				<tr>
					<td> <%= g.id_musica %></td>
					<td> <%= g.nome %></td>
					<td> 
						<%= link_to "/admin/musicas?id_musica=#{g.id_musica}&acao=editar",:class=>'btn-send' do %>
        					Editar
      					<% end %>
      					 |
      					 <%= link_to "/admin/musicas?id_musica=#{g.id_musica}&acao=apagar",:class=>'btn-send' do %>
        					Apagar
      					<% end %>

					</td>
				</tr>
			<% end %>
				
			</tbody>
		</table>

		<%= link_to "/admin/musicas" do %>
			Novo Registro
		<% end %>






	</div>

	<div class='content-overlay'>
		<%= render 'form_musica' %>
	</div>




	<style>
	.content-overlay table {
	    border-collapse: collapse;
	    width: 100%;
	}

	.content-overlay th,.content-overlay  td {
	    text-align: left;
	    padding: 8px;
	    color:#000000;
	}

	.content-overlay  tr:nth-child(even){background-color: #f2f2f2}

	.content-overlay  th {
	    background-color: #000000;
	    color: white;
	}
	</style>
	<style>
        .content-overlay .field select{
            width: 60%;
            text-align: left;
            display: inline-block;
            padding: 10px 5px;
            border-radius: 5px;
            border: 1px #cccccc solid;
            margin-left: 10px;
        }
    </style>







<% end %>