config/routes.rb
Rails.application.routes.draw do
    
    #get 'sessions/new'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #resources :favoritas
    #resources :user
    # get '/', to: 'musicas#index', as: 'index'
    root:to => 'musicas#index'
    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'
    get 'sign_out'  => 'sessions#destroy'

    get 'favoritas' =>'favoritas#index'
    

    get '/users/login' => 'users#login'

    get '/busca' => 'busca#index'

    get '/ajax/favoritar' => 'musicas#favoritar'

    post  '/admin/generos/save' => 'admin#saveGeneros'
    get '/admin/generos' => 'admin#generos'

    post  '/admin/artistas/save' => 'admin#saveArtistas'
    get '/admin/artistas' => 'admin#artistas'

    post  '/admin/musicas/save' => 'admin#saveMusicas'
    get '/admin/musicas' => 'admin#musicas'

    
    resources :users

    

    
    

end

app/views/layouts/_header.html.erb
<header>
    <div>
      <nav>
        <ul>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li>
              <ul>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li>
                  <%= link_to "Log out", sign_out_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", root_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>

		<meta charset="UTF-8">
		<title>Musical - Seu acervo favorito de músicas</title>
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<link rel="stylesheet" href="/assets/css/application.css">
        <link href="/assets/css/font-awesome.min.css" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700" rel="stylesheet">
            
	</head>
	<body>

		<aside class="sidebar">

                    <div class='logo-block'>
                        <%= link_to href: '/' do %>
                            <%= image_tag "/assets/images/logo-musical.png", width: '100%', height: 'auto', alt: 'Musical'%>
                        <% end %>
                    </div>

                    <nav class='menu-block vertical-menu'>
                        <ul>
                            <li>
                                <%= link_to '/' do %>
                                <i class='fa fa-home'></i> Home
                                <% end %>
                            </li>
                            <li>

                            <% if logged_in? %>
                                <%= link_to  "/users/#{session[:id_user]}" do %>
                                <i class='fa fa-user'></i>Minha Conta
                                <% end %>

                                <%= link_to  "/sign_out" do %>
                                <i class='fa fa-user'></i>Logout
                                <% end %>

                            <% else %>
                                <%= link_to  '/sign_in' do %>
                                <i class='fa fa-user'></i>Login
                                <% end %>


                            <% end %>

                                
                            </li>
                            <li>
                                <%= link_to '/favoritas' do %>
                                <i class='fa fa-heart'></i>Favoritas
                                <% end %>
                            </li>
                            <li>
                                <%= link_to '/busca' do %>
                                <i class='fa fa-search'></i>Buscar Músicas
                                <% end %>
                            </li>

                            <% if logged_in? %>
                                <% if current_user.tipo_usuario == 'admin' %>

                                <li>
                                    <%= link_to '/admin/generos' do %>
                                    <i class='fa fa-search'></i>Administrar Estilos
                                    <% end %>
                                </li>

                                <li>
                                    <%= link_to '/admin/artistas' do %>
                                    <i class='fa fa-search'></i>Administrar Artistas
                                    <% end %>
                                </li>

                                <li>
                                    <%= link_to '/admin/musicas' do %>
                                    <i class='fa fa-search'></i>Administrar Músicas
                                    <% end %>
                                </li>


                                <% end %>
                            <% end %>
                        </ul>
                        
                    </div>


                    <%= yield :sidebar %>
		</aside>

		<section class="content">
                  
 <% if flash[:notice] %>
    <div class="notice"><%= render html: flash[:notice].html_safe %></div>
  <% end %>

                <%= yield :content %>
		</section>

                <%= render 'partials/footer' %> 
                		
		<script src="/assets/js/jquery-3.1.1.min.js"></script>
        <script src="/assets/js/audio.min.js"></script>
        <script src="/assets/js/toastr.min.js"></script>
        <script src="/assets/js/scripts.js"></script>

        
	</body>
</html>